

export interface RawNode {
  id: number;
  name: string;
  children: RawNode[];
  depth: number;
  parent: RawNode | null;
}

// D3Node combines our RawNode with d3's simulation properties
export interface D3Node extends RawNode {
  // These properties are added by the d3 force simulation
  index?: number;
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
  fx?: number | null;
  fy?: number | null;
}

export interface D3Link {
  source: D3Node | string | number;
  target: D3Node | string | number;
  index?: number;
}

// ---- New types for Citations ----

export interface SourceArticle {
  id: string;
  source: 'SEP' | 'IEP';
  title: string;
  url: string;
}

export interface Citation {
  sourceId: string;
  sourceTitle: string;
  source: 'SEP' | 'IEP';
  url: string;
  citedText: string;
}

// ---- New types for Map Builder ----

export type RelationshipType = string;

export interface MapNode {
  id: number | string; // Use the original node ID or a generated string for AI/user nodes
  name:string;
  x: number;
  y: number;
  shape: 'rect' | 'circle';
  width: number;
  height: number;
  isAiGenerated?: boolean;
  synthesisInfo?: {
    synthesis: string;
    reasoning: string;
  };
  isHistorical?: boolean;
  isDialectic?: boolean; // For counter-arguments or figures generated by the Dialectic Engine
  isCounterExample?: boolean; // For counter-examples from definition analysis
  isUserDefined?: boolean; // For nodes created directly by the user
  textColor?: string;
  isCitation?: boolean;
  citationData?: Citation;
  notes?: string;
}

export interface MapLink {
  source: number | string; // ID of source MapNode
  target: number | string; // ID of target MapNode
  pathStyle: 'straight' | 'curved';
  relationshipTypes: RelationshipType[];
  relationshipType?: RelationshipType; // For migration from old format
  justification?: string | { text: string; citations: Citation[] }; // Updated to support structured justifications
  justificationState?: 'idle' | 'loading' | 'success' | 'error';
  implications?: string[];
  implicationsState?: 'idle' | 'loading' | 'success' | 'error';
  isHistorical?: boolean;
  isCounterExampleLink?: boolean;
  formalizationState?: 'idle' | 'loading' | 'success' | 'error';
  formalRepresentation?: string;
}

export interface FormalizationChoice {
    formalRepresentation: string;
    suggestedSystem: string;
    rationale: string;
}

export interface FormalizationResult {
    choices: FormalizationChoice[];
    critique: string;
    propositions: { variable: string; meaning: string }[];
}

export interface LogicalConstruct {
    id: string;
    premiseNodeIds: (string | number)[];
    conclusionNodeId: string | number;
    operator: 'AND'; // Can be extended to 'OR', etc. in the future
    formalRepresentation: string;
    critique: string;
    propositions: { variable: string; meaning:string }[];
    suggestedSystem: string;
    rationale: string;
}

// --- Types for Feed Page ---
export interface TrackedFeed {
    id: string; // url can be the id
    url: string;
    nodeId: number;
    nodeName: string;
    error?: string | null;
    isLoading?: boolean;
}

export interface Publication {
    title: string;
    author: string | null;
    publicationInfo: string | null;
    link: string;
    sourceNodeName: string; // The name of the category/node this feed belongs to
    sourceUrl: string; // To identify which feed it belongs to
    isNew?: boolean;
}

// --- Types for Project Diary ---
export type ProjectActivityType =
  | 'EXPLORE_CONCEPT'
  | 'FIND_RELATED'
  | 'ADD_TO_TRAY'
  | 'CREATE_MAP_LINK'
  | 'ADD_FEED'
  | 'VIEW_PUBLICATION'
  | 'ANALYZE_GENEALOGY'
  | 'EXPLORE_IMPLICATIONS'
  | 'CHANGE_CONCEPT'
  | 'SYNTHESIZE_REGION'
  | 'ANALYZE_ARGUMENT'
  | 'FORMALIZE_ARGUMENT'
  | 'CREATE_USER_NODE'
  | 'CREATE_LOGICAL_CONSTRUCT'
  | 'GENERATE_JUSTIFICATION'
  | 'ANALYZE_DEFINITION'
  | 'EDIT_NOTE';

export interface ProjectActivity {
  id: string;
  timestamp: number;
  type: ProjectActivityType;
  payload: {
    provenance?: {
        prompt: string;
        systemInstruction?: string;
        rawResponse: string;
        model: string;
    };
    [key: string]: any;
  };
}

// --- Type for Relationship Types ---
export interface CustomRelationshipType {
    name: string;
    description: string;
    color: string;
}


// --- Type for Data Portability ---
export interface AppSessionData {
    trackedFeeds: TrackedFeed[];
    mapLayout: { 
        nodes: MapNode[], 
        links: MapLink[],
        logicalConstructs: LogicalConstruct[],
    };
    mapTrayConceptIds: number[];
    seenPublicationIds: string[];
    projectDiary: ProjectActivity[];
}

export interface Project {
  id: string;
  name: string;
  data: AppSessionData;
}

export interface MultiProjectSession {
  version: number;
  activeProjectId: string | null;
  projects: Project[];
  customRelationshipTypes: CustomRelationshipType[];
  disabledDefaultTypes: string[];
  disabledCustomTypes: string[];
}

// --- Types for Definition Analysis ---
export interface DefinitionResult {
    source: string;
    summary: string;
}

export interface CounterExampleResult {
    counterExample: string;
    justification: string;
}

export interface DefinitionAnalysisState {
    x: number;
    y: number;
    link: MapLink;
    sourceNodeName: string;
    targetNodeName: string;
    loadingState: 'idle' | 'loadingDefinitions' | 'loadingCounterExamples';
    definitions: DefinitionResult[];
    counterExamples: Map<DefinitionResult, CounterExampleResult[]>;
    error: string | null;
}