import { WikiSource, WikiCategoryEntry } from '../types';

/**
 * Resolves a given raw name or bullet key to the closest standard taxonomy category name.
 * Uses exact-word-boundary matching on English category names and standard Portuguese translations.
 */
export function resolveToTaxonomyCategory(name: string, taxonomyCategories: string[]): string {
    const cleanName = name.trim();
    if (!cleanName) return "";

    const PT_TO_EN_MAP: { [key: string]: string } = {
        'normatividade epistemica': 'Epistemic Normativity',
        'voluntarismo doxastico': 'Doxastic Voluntarism',
        'etica da crenca': 'Ethics of Belief',
        'etica de crenca': 'Ethics of Belief',
        'akrasia epistemica': 'Epistemic Akrasia',
        'acrasia epistemica': 'Epistemic Akrasia',
        'ceticismo': 'Skepticism',
        'testemunho': 'Testimony',
        'inducao': 'Induction',
        'razoes epistemicas': 'Epistemic Reasons',
        'justificacao': 'Justification',
        'virtudes epistemicas': 'Epistemic Virtues',
        'percepcao': 'Perception',
        'auto-conhecimento': 'Self-Knowledge',
        'autoconhecimento': 'Self-Knowledge',
        'memoria': 'Memory',
        'verdade': 'Truth',
        'conhecimento': 'Knowledge',
        'filosofia da mente': 'Philosophy of Mind',
        'filosofia da acao': 'Philosophy of Action',
        'livre arbitrio': 'Free Will',
        'motivacao': 'Motivation',
        'crenca': 'Belief',
        'desejo': 'Desire',
        'emocao': 'Emotion',
        'ideias': 'Ideas',
        'imaginacao': 'Imagination',
        'dor': 'Pain',
        'prazer': 'Pleasure',
        'meta-etica': 'Meta-Ethics',
        'meta-ética': 'Meta-Ethics',
        'etica normativa': 'Normative Ethics',
        'psicologia moral': 'Moral Psychology',
        'utilitarismo': 'Utilitarianism',
        'etica das virtudes': 'Virtue Ethics',
        'justica': 'Justice',
        'racionalidade': 'Rationality',
        'evidencia': 'Evidence',
        'fraqueza da vontade': 'Weakness of Will',
        'razao pratica': 'Practical Reason',
        'natureza da crenca': 'The Nature of Belief',
    };

    const normalizeText = (text: string): string => {
        return text
            .toLowerCase()
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "") // remove accents/diacritics
            .replace(/[^a-z0-9]/g, " ") // only alphanumeric
            .replace(/\s+/g, " ")
            .trim();
    };

    const normName = " " + normalizeText(cleanName) + " ";

    interface MatchInfo {
        category: string;
        startIndex: number;
        length: number;
    }
    const matches: MatchInfo[] = [];

    // Exact word boundary matching on English categories
    taxonomyCategories.forEach(cat => {
        const normCat = normalizeText(cat);
        if (!normCat) return;

        const matchIdx = normName.indexOf(" " + normCat + " ");
        if (matchIdx !== -1) {
            matches.push({
                category: cat,
                startIndex: matchIdx,
                length: normCat.length
            });
        }
    });

    // Exact word boundary matching on Portuguese terms
    Object.keys(PT_TO_EN_MAP).forEach(ptKey => {
        const normPt = normalizeText(ptKey);
        if (normName.includes(" " + normPt + " ")) {
            const enCat = PT_TO_EN_MAP[ptKey];
            const matchedEnCat = taxonomyCategories.find(c => normalizeText(c) === normalizeText(enCat));
            if (matchedEnCat) {
                matches.push({
                    category: matchedEnCat,
                    startIndex: normName.indexOf(" " + normPt + " "),
                    length: normPt.length
                });
            }
        }
    });

    if (matches.length === 0) return "";

    // Prefer longer/more specific sub-matches and discard smaller substrings
    const filteredMatches = matches.filter(m1 => {
        return !matches.some(m2 => m2 !== m1 && m2.category.toLowerCase().includes(m1.category.toLowerCase()) && m2.length > m1.length);
    });

    if (filteredMatches.length === 0) return "";

    // Sort: latest match in the string representing the specific subcategory (right-to-left) gets preference, then length
    filteredMatches.sort((a, b) => {
        if (b.startIndex !== a.startIndex) {
            return b.startIndex - a.startIndex;
        }
        return b.length - a.length;
    });

    return filteredMatches[0].category;
}

/**
 * Parses markdown/text generated by an LLM matching structured layouts.
 * Returns a WikiSource (representing the article/book chapter read) and a list of
 * WikiCategoryEntry items.
 */
export function parseWikiStructuredText(rawText: string, taxonomyCategories?: string[]): { 
    source: Omit<WikiSource, 'id' | 'createdAt'>; 
    entries: Omit<WikiCategoryEntry, 'id' | 'sourceId' | 'sourceTitle' | 'sourceAuthor'>[];
} {
    const lines = rawText.split('\n');
    const cats = taxonomyCategories || [];

    // Metadata & Summary Extraction variables
    let title = "Untitled Reading";
    let author = "Unknown Author";
    let type: 'article' | 'book' | 'chapter' = 'article';
    let generalSummaryLines: string[] = [];

    // Helper to see if a line matches a category
    const getCategoryMatchForLine = (line: string): string => {
        const trimmed = line.trim();
        if (!trimmed) return "";

        // Reject immediate metadata or paths to prevent duplicate triggers
        if (/caminho/i.test(trimmed) || /path/i.test(trimmed) || /philpapers/i.test(trimmed)) {
            return "";
        }
        
        // Ensure safe checks on candidate triggers
        const hasPathToken = trimmed.includes(' > ');
        const isBulletAndBold = /^([\*\-\+]\s*|\d+\.\s*)/.test(trimmed) && trimmed.includes('**');
        const isHeading = trimmed.startsWith('#');
        const resolvedDirectly = resolveToTaxonomyCategory(trimmed, cats);

        if (resolvedDirectly) {
            // Keep it very precise: if it is a heading, a path line, or starts with a bold category Bullet, it is a Match!
            if (isHeading || hasPathToken || isBulletAndBold || (trimmed.length - resolvedDirectly.length < 25)) {
                return resolvedDirectly;
            }
        }
        return "";
    };

    // Parse loop parameters
    interface RawCategoryBlock {
        categoryName: string;
        lines: string[];
    }
    const rawBlocks: RawCategoryBlock[] = [];
    let currentBlock: RawCategoryBlock | null = null;
    let foundAnyCategoryTrigger = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const trimmed = line.trim();

        // 1. Look for explicit metadata overrides (Title, Author, Type)
        const tMatch = line.match(/(?:título|title)\s*:\s*(.+)/i);
        if (tMatch) {
            title = tMatch[1].replace(/["'“«»”*_]/g, '').trim();
            continue;
        }
        const aMatch = line.match(/(?:autor|author)\s*:\s*(.+)/i);
        if (aMatch) {
            author = aMatch[1].replace(/[*_]/g, '').trim();
            continue;
        }
        const tyMatch = line.match(/(?:tipo|type)\s*:\s*(.+)/i);
        if (tyMatch) {
            const tyVal = tyMatch[1].toLowerCase();
            if (tyVal.includes('livro') || tyVal.includes('book') || tyVal.includes('obra')) {
                type = 'book';
            } else if (tyVal.includes('capítulo') || tyVal.includes('chapter')) {
                type = 'chapter';
            } else {
                type = 'article';
            }
            continue;
        }

        // 2. Check if this line triggers a new category
        const triggeredCatName = getCategoryMatchForLine(line);
        if (triggeredCatName) {
            foundAnyCategoryTrigger = true;
            // Complete previous block if existing
            if (currentBlock) {
                rawBlocks.push(currentBlock);
            }
            currentBlock = {
                categoryName: triggeredCatName,
                lines: [line]
            };
        } else {
            if (!foundAnyCategoryTrigger) {
                // Collect lines of general summary
                if (trimmed && !trimmed.startsWith('#')) {
                    generalSummaryLines.push(line);
                }
            } else if (currentBlock) {
                // Collect details under active category
                currentBlock.lines.push(line);
            }
        }
    }

    // Push final active block
    if (currentBlock) {
        rawBlocks.push(currentBlock);
    }

    // Build the general summary text from collected lines
    let generalSummary = generalSummaryLines.slice(0, 10).join('\n').trim();

    // Fallback title / author extraction if not directly defined by metadata keywords
    if (title === "Untitled Reading" && generalSummary) {
        const titleRegexMatch = generalSummary.match(/"([^"]+)"|“([^”]*)”|«([^»]*)»|'([^']+)'/);
        if (titleRegexMatch) {
            title = titleRegexMatch[1] || titleRegexMatch[2] || titleRegexMatch[3] || titleRegexMatch[4];
        } else {
            const articleMatch = generalSummary.match(/artigo\s+([^,]+),/i);
            if (articleMatch) {
                title = articleMatch[1].replace(/[*_]/g, '').trim();
            }
        }
    }

    if (author === "Unknown Author" && generalSummary) {
        const authorMatch = generalSummary.match(/(?:escrito por|por|autor)\s+([A-ZÀ-ÖØ-ß][a-zà-öø-ÿ]+(?:\s+[A-ZÀ-ÖØ-ß][a-zà-öø-ÿ]+)+)/) ||
                            generalSummary.match(/([A-ZÀ-ÖØ-ß][a-zà-öø-ÿ]+(?:\s+[A-ZÀ-ÖØ-ß][a-zà-öø-ÿ]+)+)\s+(?:investiga|analisa|argumenta|explora)/);
        if (authorMatch) {
            author = authorMatch[1].trim();
        }
    }

    // Refined type extraction from summary text
    if (generalSummary) {
        const lowerSummary = generalSummary.toLowerCase();
        if (lowerSummary.includes('livro') || lowerSummary.includes('book') || lowerSummary.includes('obra')) {
            type = 'book';
        } else if (lowerSummary.includes('capítulo') || lowerSummary.includes('chapter')) {
            type = 'chapter';
        }
    }

    // Clean up category entries
    const rawEntries: Omit<WikiCategoryEntry, 'id' | 'sourceId' | 'sourceTitle' | 'sourceAuthor'>[] = [];

    rawBlocks.forEach(block => {
        const cleanedLines = block.lines
            .map(line => {
                let cleaned = line.trim();
                // Skip path indicator lines completely to avoid raw tree junk in the notes
                if (cleaned.includes(' > ')) {
                    return "";
                }
                // Strip markdown headers or bullet marks
                cleaned = cleaned.replace(/^#+\s*/, '');
                cleaned = cleaned.replace(/^([\*\-\+]\s*|\d+\.\s*)/, '');
                // Neutralize prefix structures like "Caminho PhilPapers:", etc.
                cleaned = cleaned.replace(/^(\*Caminho\*|Caminho|Caminho PhilPapers.*?)\s*:\s*/i, '');

                // Strip "Categoria: [Name]" prefixes (case-insensitive) often seen on AI-generated lines
                cleaned = cleaned.replace(/^categoria\s*:\s*[\w\s\-\(\)\/\>\,\.\&\+áéíóúâêîôûãõçÁÉÍÓÚÂÊÎÔÛÃÕÇ]+?(?=notas\s+de\s+debate|$)/i, '');

                // Strip "Notas de Debate: [Details] (Eixo [Numbers])" prefix patterns (case-insensitive)
                cleaned = cleaned.replace(/^notas\s+de\s+debate\s*:\s*.*?\((?:eixo|eixos)\s*\d+.*?\)\.?\s*/i, '');

                // Neutralize other standalone "Notas de Debate:" prefix structures
                cleaned = cleaned.replace(/^notas\s+de\s+debate\s*:\s*/i, '');

                return cleaned.trim();
            })
            .filter(Boolean);

        const notesText = cleanedLines.join('\n').trim();
        if (notesText) {
            rawEntries.push({
                categoryName: block.categoryName,
                notes: notesText
            });
        }
    });

    // Deduplicate and merge same category blocks to prevent duplicate sources count
    const entriesMap = new Map<string, string>();
    rawEntries.forEach(ent => {
        const existing = entriesMap.get(ent.categoryName);
        if (existing) {
            // Only append if it's not already sub-contained in existing to prevent exact repeat lines
            if (!existing.includes(ent.notes)) {
                entriesMap.set(ent.categoryName, existing + '\n\n' + ent.notes);
            }
        } else {
            entriesMap.set(ent.categoryName, ent.notes);
        }
    });

    const entries: Omit<WikiCategoryEntry, 'id' | 'sourceId' | 'sourceTitle' | 'sourceAuthor'>[] = [];
    entriesMap.forEach((notes, categoryName) => {
        entries.push({ categoryName, notes });
    });

    return {
        source: {
            title: title || "Untitled Reading",
            author: author || "Unknown Author",
            type,
            generalSummary: generalSummary || "Mapeamento carregado na Ágora de debate."
        },
        entries
    };
}
